### ISSUE TITLE
Training AWE 

### ISSUE THREAD

**Issue by xorsuyash** [DataGov-SamagraX/hindi-acoustic-word-embedding#1]
**Tasks**
- [x] Coding architecture of AWE model.
- [x] Setting up training and testing pipeline, dataloader + trainer 
- [ ] Devising better strategy for force alignment 
- [ ] Integrate ASR in force alignment if transcript is not available possilble( ai4bharat + kenLM) 
- [ ] Devising strategy to cut and merge using voice activity detection for incoming audio in force aligner.

**Comment by xorsuyash** [comment]
@GautamR-Samagra coded architecture of AWE in a proper setting, setting up testing pipeline and eval pipeline.
